# action.yml
name: 'Secret Job'
description: 'Testing inputs'
author: Vlado Bosnjak <hi@codesoup.co>
inputs:
  host:  # id of input
    description: 'Who to greet'
    required: true
    default: 'my-host'
  secret:  # id of input
    description: 'Who to greet'
    required: true
    default: 'my-secret'
runs:
  using: 'docker'
  image: 'Dockerfile'